### PR TITLE
Jroach/us126105

### PR DESCRIPTION
**Pull request by jeroach**
[US126105](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F512303623704&fdp=true?fdp=true): [Consistent Evaluation][Discussions][UI] Implement d2l-table in consistent-evaluation-evidence-discussion

image

image

### CODE REVIEW

**Comment by amauryperez** [comment]
LGTM, the only thing I'm noticing in the image is that the `unscored` icon in the header does not look vertically centered.

**Comment by jeroach** [comment]
> LGTM, the only thing I'm noticing in the image is that the `unscored` icon in the header does not look vertically centered.

good point, I'll see if I can tweak that :)

**Review by amauryperez — APPROVED** [review]

**Comment by jeroach** [comment]
> Also, do the cells have too much space top and bottom? Or is that per the design?

I can run it by Fiona - I just took the existing spacing logic and dropped it in `d2l-table`

**Comment by jeroach** [comment]
Design does look to be tighter - I bet `d2l-table` has it's own spacing and now we're doubling up.

The scored thing is centered too: https://xd.adobe.com/view/1f5fb770-bb62-4dfd-8e74-b500a4eafb54-4a0c/screen/884fc92e-ccf9-438b-a478-4309b39b7811

**Review by JamieTran — APPROVED** [review]
LGTM! I think we want the score column to be the size of the `grade-component`
image

**Review by JamieTran — APPROVED** [review]
Byootiful!!!

**Review by amauryperez — APPROVED** [review]

**Pull request merged**
