### PR TITLE
Evaluation navigate with unsaved changes dialog overhaul

### PR DESCRIPTION
**Pull request by tdevos-d2l**
Rewording the unsaved changes when navigating dialog
Added functionality to 'Save' or 'Discard' and navigate

New dialog:
image

### CODE REVIEW

**Comment by vix633** [comment]
> Rewording the unsaved changes when navigating dialog
> Added functionality to 'Save' or 'Discard' and navigate
> 
> New dialog:
> image

What's the default option here? If someone hits the dialog and hits enter hastily, what would happen?

**Comment by tdevos-d2l** [comment]
Discard I think... not so good, let me change that

**Comment by tdevos-d2l** [comment]
New dialog now defaults focus to 'Save'
Good for review now.

image

**Review by vix633 — APPROVED** [review]
:shipit:

**Review by maddiegabriel — APPROVED** [review]
💯 🥇 👍

**Pull request merged**
