### PR TITLE
add note about PR approvals

### PR DESCRIPTION
**Pull request by jeroach**
As per suggestion from this Slack thread: https://d2l.slack.com/archives/CSL64JP9U/p1638892099143100

### CODE REVIEW

**Comment by jeroach** [comment]
Looks like it worked :) 

image

**Comment by Scy-D2L** [comment]
> Visual diff tests failed - pull request #801 has been opened with the updated goldens.

This is more profile-card vdiff flake 🤔 If it keeps happening we might need to address it.

**Review by Scy-D2L — APPROVED** [review]

**Comment by jeroach** [comment]
> 

Ugh....failed again...

**Comment by Scy-D2L** [comment]
> > 
> 
> Ugh....failed again...

Short term option: It's possible our vdiff is the less-likely flake state. I would be ok with just accepting it here to get this through and watching to see if we keep having issues.

**Comment by jeroach** [comment]
> > > 
> > 
> > 
> > Ugh....failed again...
> 
> Short term option: It's possible our vdiff is the less-likely flake state. I would be ok with just accepting it here to get this through and watching to see if we keep having issues.

Works for me :)

**Pull request merged**
