### PR TITLE
DE46320 - Mobile RTL Assignment Feedback Alignment Bug Fix

### PR DESCRIPTION
**Pull request by Girujan1998**
Rally: https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F618900146199

Fixing alignment of grade feedback for assignments in RTL for mobile.

**Before**
mobileRTL

**After**

### CODE REVIEW

**Comment by Scy-D2L** [comment]
I see the screenshot from the rally story - can you add a screenshot of what it looks like with the changes? 📷

**Comment by Girujan1998** [comment]
> I see the screenshot of the 'before' problem from the rally story - can you add a screenshot of what it looks like with the changes? 📷

After image added in description.

**Review by maddiegabriel — APPROVED** [review]
First PR looks great to me! 🥳 
I think Scy is off this week - feel free to add another nimbus-er to review 👍

**Review by JamieTran — APPROVED** [review]
lgtm!

**Pull request merged**
